services:
  api:
    image: grzybb23/cloudproject-back:latest
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    env_file:
      - ./server/.env
    networks:
      - app-network

  frontend:
    image: grzybb23/cloudproject-front:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - ./client/.env
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
