name: Deploy Frontend and Backend to Mikrus

on:
  push:
    branches:
      - main  # Workflow działa na głównej gałęzi

jobs:
  build-and-deploy-backend:
    name: Build and Deploy Backend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build backend Docker image
      run: |
        docker build -t grzybb23/cloudproject-back:latest ./server

    - name: Push backend Docker image to Docker Hub
      run: |
        docker push grzybb23/cloudproject-back:latest

    - name: Deploy backend to Mikrus
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: "[2a01:4f9:6a:1cc8::234]"
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull grzybb23/cloudproject-back:latest
          docker stop libraryapp-backend || true
          docker rm cloudproject-back || true
          docker run -d --name cloudproject-back -p 5000:5000 grzybb23/cloudproject-back:latest

  build-and-deploy-frontend:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build frontend Docker image
      run: |
        docker build -t grzybb23/cloudproject-front:latest ./client

    - name: Push frontend Docker image to Docker Hub
      run: |
        docker push grzybb23/cloudproject-front:latest

    - name: Deploy frontend to Mikrus
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: "[2a01:4f9:6a:1cc8::234]"
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull grzybb23/cloudproject-front:latest
          docker stop cloudproject-front || true
          docker rm cloudproject-front || true
          docker run -d --name cloudproject-front -p 3000:3000 grzybb23/cloudproject-front:latest
